version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7.0.15
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 3s

  app:
    build: .
    restart: always
    depends_on:
        - db
        - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/ecommerce
      REDIS_URL: redis://redis:6379/1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - .:/rails
      - bundle_cache:/bundle
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && ./entrypoint.sh"]

volumes:
  postgres_data:
  bundle_cache:
