:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    mark_abandoned_carts:
      cron: "0 * * * *"  # Executa a cada 1 hora
      class: "MarkCartAsAbandonedJob"
      queue: default
    delete_abandoned_carts:
      cron: "0 0 * * *"  # Executa todos os dias à meia-noite UTC
      class: "DeleteAbandonedCartsJob"
      queue: default
